server:
  port: 8082

spring:
  application:
    name: risque-service

eureka:
  client:
    service-url:
      defaultZone: http://discovery-service:8761/eureka/
    fetch-registry: true
    register-with-eureka: true
    registry-fetch-interval-seconds: 5
  instance:
    prefer-ip-address: true
    hostname: risque-service

logging:
  level:
    root: INFO
    com.medicolab.risque: DEBUG