server:
  port: 8081

spring:
  application:
    name: security-config

eureka:
  instance:
    hostname: security-config
  client:
    service-url:
      defaultZone: http://discovery-service:8761/eureka